swagger: '2.0'
info:
  description: |
    ENMS Notification RESTful interface.
  version: 0.3.0
  title: Notification API
basePath: /
schemes:
  - http
  - https
  
paths:
  '/enms/notifications':
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAllNotifications  
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Message'
              
  /enms/alarms:
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAllAlarms
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Alarm'
              
  '/enms/alarms/severity/{severity}':
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAlarmsBySeverity
      parameters:
        - name: severity
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Alarm'
        400:
          description: Invalid parameter
        404:
          description: 'no alarms found'
              
  '/enms/alarms/ne/{neid}':
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAlarmsByNe
      parameters:
        - in: path
          name: neid
          description: NEID of TP that needs to be fetched
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Alarm'
        '400':
          description: Invalid NE ID supplied
        '404':
          description: TP not found


definitions:

  Message:
    type: object
    properties:
      sender:
        type: string
        description: 'the info of sender, for example: adapter-1 '
      messageType:
        type: string
        description: alarm, avc(attribute value change), oc(object creation), od(object deletion)
      alarm:
        $ref: '#/definitions/Alarm'    
      avcs:
        type: array
        items:
          $ref: '#/definitions/AvcBody'
      ocDetail:
        $ref: '#/definitions/OcBody'
      odDetail:
        $ref: '#/definitions/OdBody'

  AvcBody:    
    type: object
    description: Attribute value change details
    properties:
      eventTime:
        type: string
        description: the time of the event
      objectType:
        type: string
        description: 'the object type of the notification: NE, Board, TP, Connection'
      objectID:
        type: string
        description: the ID of the target Object.
      key:
        type: string
        description: the keyof changed field
      valueType:
        type: string
        description: "the attribute's type: int, string, boolean etc. "
      value:
        type: string
      oldValue:
        type: string
          
  OcBody:    
    type: object
    description: Object Creation notification
    properties:
      eventTime:
        type: string
        description: the time of the event
      objectType:
        type: string
        description: 'the object type of the notification: NE, Board, TP, Connection'
      objectID:
        type: string
        description: the ID of the target Object.

  OdBody:    
    type: object
    description: Object deletion notification
    properties:
      eventTime:
        type: string
        description: the time of the event
      objectType:
        type: string
        description: 'the object type of the notification: NE, Board, TP, Connection'
      objectID:
        type: string
        description: the ID of the target Object.

  Alarm:
    type: object
    properties:
      alarmCode:
        type: string
      alarmType:
        type: string
      severity:
        type: string
        description: severity of alarm, MAJOR, MINOR,CRITICAL,INFO,WARNING,CLEARED
      eventTime:
        type: string
        description: the time of the event on host, such as Adapter host's time
      occureTime:
        type: string
        description: the time of the alarm on NE
      clearTime:
        type: string
      probableCause:
        type: string
      objectType:
        type: string
        description: the object type of the alarm
      objectId:
        type: string
        description: the object id
      ackStatus:
        type: string
        description: acknowledgement status, true or false
      ackTime:
        type: string
        description: acknowledgement time
#      resvStatus:
#        type: string
#        description: reservation status
      description:
        type: string

