swagger: '2.0'
info:
  description: |
    ENMS Notification RESTful interface.
  version: 0.3.0
  title: Notification API
basePath: /
schemes:
  - http
  - https
  
paths:
  '/enms/notifications':
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAllNotifications  
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Message'
              
  /enms/alarms:
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAllAlarms
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Alarm'
              
  '/enms/alarms/level/{severity}':
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAlarmsBySeverity
      parameters:
        - name: severity
          in: path
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Alarm'
        400:
          description: Invalid parameter
        404:
          description: 'no alarms found'
              
  '/enms/alarms/ne/{neid}':
    get:
      tags:
        - msgSystem
      produces:
        - application/json
      operationId: getAlarmsByNe
      parameters:
        - in: path
          name: neid
          description: NEID of TP that needs to be fetched
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Alarm'
        '400':
          description: Invalid NE ID supplied
        '404':
          description: TP not found


definitions:

  Message:
    type: object
    properties:
      sender:
        type: string
        description: 'the info of sender, for example: adapter-1 '
      messageType:
        type: string
        description: notification or alarm
      sendTime:
        type: string
      notification:
        $ref: '#/definitions/Notification'
      alarm:
        $ref: '#/definitions/Alarm'    

  Notification:
    type: object
    properties:
      type:
        type: string
        description: the overall notification type, add,delete or update
      objectType:
        type: string
        description: 'the object type of the notification: NE, Board, TP, Connection'
      objectID:
        type: string
        description: the ID of the target Object.
      avcDetails:
        type: array
        items:
          $ref: '#/definitions/AvcDetail'
          
  AvcDetail:    
    type: object
    description: Attribute value change details
    properties:
      key:
        type: string
      valueType:
        type: string
        description: "the attribute's type: int, string, boolean etc. "
      value:
        type: string
      oldValue:
        type: string
          
  Alarm:
    type: object
    properties:
      alarmCode:
        type: string
      alarmType:
        type: string
      severity:
        type: string
        description: severity of alarm, MAJOR, MINOR,CRITICAL,INFO,WARNING
      occureTime:
        type: string
      clearTime:
        type: string
      probableCause:
        type: string
      objectType:
        type: string
        description: the object type of the alarm
      moc:
        type: string
        description: the management object class
      alarmObject:
        type: string
      ackStatus:
        type: string
        description: acknowledgement status, true or false
      resvStatus:
        type: string
        description: reservation status
      description:
        type: string

